// <auto-generated />
using System;
using ImsaFantasy.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImsaFantasy.Infrastructure.Migrations
{
    [DbContext(typeof(FantasyDbContext))]
    [Migration("20260703201502_AddEventPicksOpenedAt")]
    partial class AddEventPicksOpenedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImsaFantasy.Domain.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailSuppressedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_suppressed_at");

                    b.Property<string>("ExternalProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_provider");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("ExternalProvider", "ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_external_provider_external_subject");

                    b.ToTable("app_user");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.CarEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team_name");

                    b.HasKey("Id")
                        .HasName("pk_car_entry");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_car_entry_class_id");

                    b.HasIndex("SeasonId", "ClassId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_car_entry_season_id_class_id_number");

                    b.ToTable("car_entry");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Championship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_championship");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_championship_slug");

                    b.ToTable("championship");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChampionshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("championship_id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_class");

                    b.HasIndex("ChampionshipId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_class_championship_id_name");

                    b.ToTable("class");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_driver");

                    b.ToTable("driver");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EmailEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("SesMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ses_message_id");

                    b.Property<string>("SnsMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sns_message_id");

                    b.Property<string>("Subtype")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("subtype");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_event");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_email_event_email");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_event_user_id");

                    b.HasIndex("SnsMessageId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_email_event_sns_message_id_email")
                        .HasFilter("sns_message_id IS NOT NULL");

                    b.ToTable("email_event");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EmailPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_preference");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_email_preference_user_id_kind");

                    b.ToTable("email_preference");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EntityPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("entity_type");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.HasKey("Id")
                        .HasName("pk_entity_price");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_entity_price_class_id");

                    b.HasIndex("RoundId", "EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_price_round_id_entity_type_entity_id");

                    b.ToTable("entity_price");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EntryDriver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CarEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("car_entry_id");

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint")
                        .HasColumnName("driver_id");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_entry_driver");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_entry_driver_driver_id");

                    b.HasIndex("CarEntryId", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("ix_entry_driver_car_entry_id_driver_id");

                    b.ToTable("entry_driver");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Circuit")
                        .HasColumnType("text")
                        .HasColumnName("circuit");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("PicksOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("picks_open");

                    b.Property<DateTime?>("PicksOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picks_opened_at");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_event");

                    b.ToTable("event");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EventReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SesMessageId")
                        .HasColumnType("text")
                        .HasColumnName("ses_message_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_event_reminder");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_reminder_user_id");

                    b.HasIndex("EventId", "UserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_event_reminder_event_id_user_id_kind");

                    b.ToTable("event_reminder");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.League", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("JoinCode")
                        .HasColumnType("text")
                        .HasColumnName("join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OwnerRegistrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_registration_id");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_league");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_league_join_code");

                    b.HasIndex("OwnerRegistrationId")
                        .HasDatabaseName("ix_league_owner_registration_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_league_season_id");

                    b.ToTable("league");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.LeagueMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_id");

                    b.Property<long>("RegistrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("registration_id");

                    b.HasKey("Id")
                        .HasName("pk_league_membership");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("ix_league_membership_registration_id");

                    b.HasIndex("LeagueId", "RegistrationId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_membership_league_id_registration_id");

                    b.ToTable("league_membership");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Pick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("entity_type");

                    b.Property<decimal>("PriceAtLock")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_at_lock");

                    b.Property<long>("RosterId")
                        .HasColumnType("bigint")
                        .HasColumnName("roster_id");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("slot_type");

                    b.HasKey("Id")
                        .HasName("pk_pick");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_pick_class_id");

                    b.HasIndex("RosterId", "SlotType", "EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_pick_roster_id_slot_type_entity_type_entity_id");

                    b.ToTable("pick");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.PositionPoints", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Points")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("points");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<long>("RulesetId")
                        .HasColumnType("bigint")
                        .HasColumnName("ruleset_id");

                    b.HasKey("Id")
                        .HasName("pk_position_points");

                    b.HasIndex("RulesetId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ix_position_points_ruleset_id_rank");

                    b.ToTable("position_points");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.QualiResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BestLapMs")
                        .HasColumnType("bigint")
                        .HasColumnName("best_lap_ms");

                    b.Property<long>("CarEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("car_entry_id");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_quali_result");

                    b.HasIndex("CarEntryId")
                        .HasDatabaseName("ix_quali_result_car_entry_id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_quali_result_class_id");

                    b.HasIndex("SessionId", "CarEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_quali_result_session_id_car_entry_id");

                    b.ToTable("quali_result");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RaceFastestLap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint")
                        .HasColumnName("driver_id");

                    b.Property<long>("FastestLapMs")
                        .HasColumnType("bigint")
                        .HasColumnName("fastest_lap_ms");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_race_fastest_lap");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_race_fastest_lap_class_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_race_fastest_lap_driver_id");

                    b.HasIndex("SessionId", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("ix_race_fastest_lap_session_id_driver_id");

                    b.ToTable("race_fastest_lap");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RaceResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CarEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("car_entry_id");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<int?>("Laps")
                        .HasColumnType("integer")
                        .HasColumnName("laps");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_race_result");

                    b.HasIndex("CarEntryId")
                        .HasDatabaseName("ix_race_result_car_entry_id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_race_result_class_id");

                    b.HasIndex("SessionId", "CarEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_race_result_session_id_car_entry_id");

                    b.ToTable("race_result");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Registration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team_name");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_registration");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_registration_season_id");

                    b.HasIndex("UserId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_user_id_season_id");

                    b.ToTable("registration");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Roster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<long>("RegistrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("registration_id");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roster");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_roster_round_id");

                    b.HasIndex("RegistrationId", "RoundId")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_registration_id_round_id");

                    b.ToTable("roster");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RosterModifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("params");

                    b.Property<long>("RosterId")
                        .HasColumnType("bigint")
                        .HasColumnName("roster_id");

                    b.Property<long?>("TargetPickId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_pick_id");

                    b.HasKey("Id")
                        .HasName("pk_roster_modifier");

                    b.HasIndex("TargetPickId")
                        .HasDatabaseName("ix_roster_modifier_target_pick_id");

                    b.HasIndex("RosterId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_modifier_roster_id_kind");

                    b.ToTable("roster_modifier");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RosterModifierRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("applies_to");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_count");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_roster_modifier_rule");

                    b.HasIndex("SeasonId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_modifier_rule_season_id_kind");

                    b.ToTable("roster_modifier_rule");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RosterRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<int>("MaxPicks")
                        .HasColumnType("integer")
                        .HasColumnName("max_picks");

                    b.Property<int>("MinPicks")
                        .HasColumnType("integer")
                        .HasColumnName("min_picks");

                    b.Property<long?>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("slot_type");

                    b.HasKey("Id")
                        .HasName("pk_roster_rule");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_roster_rule_class_id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_roster_rule_round_id");

                    b.HasIndex("SeasonId", "RoundId", "ClassId", "SlotType")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_rule_season_id_round_id_class_id_slot_type");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("SeasonId", "RoundId", "ClassId", "SlotType"), false);

                    b.ToTable("roster_rule");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Round", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Circuit")
                        .HasColumnType("text")
                        .HasColumnName("circuit");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("QualiStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quali_start");

                    b.Property<decimal>("SalaryCap")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("salary_cap");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_round");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_round_event_id");

                    b.HasIndex("SeasonId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_round_season_id_sequence");

                    b.ToTable("round");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RoundTotal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Points")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("points");

                    b.Property<long>("RegistrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("registration_id");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_round_total");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_round_total_round_id");

                    b.HasIndex("RegistrationId", "RoundId")
                        .IsUnique()
                        .HasDatabaseName("ix_round_total_registration_id_round_id");

                    b.ToTable("round_total");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<long?>("PickId")
                        .HasColumnType("bigint")
                        .HasColumnName("pick_id");

                    b.Property<decimal>("Points")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("points");

                    b.Property<long>("RosterId")
                        .HasColumnType("bigint")
                        .HasColumnName("roster_id");

                    b.Property<long?>("RosterModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("roster_modifier_id");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_score");

                    b.HasIndex("RosterId")
                        .HasDatabaseName("ix_score_roster_id");

                    b.HasIndex("PickId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_score_pick_id_source")
                        .HasFilter("pick_id IS NOT NULL");

                    b.HasIndex("RosterModifierId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_score_roster_modifier_id_source")
                        .HasFilter("roster_modifier_id IS NOT NULL");

                    b.ToTable("score", t =>
                        {
                            t.HasCheckConstraint("ck_score_one_owner", "(pick_id IS NULL) <> (roster_modifier_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ImsaFantasy.Domain.ScoreAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<decimal>("NewPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("new_points");

                    b.Property<decimal>("OldPoints")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("old_points");

                    b.Property<long?>("PickId")
                        .HasColumnType("bigint")
                        .HasColumnName("pick_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long?>("RosterModifierId")
                        .HasColumnType("bigint")
                        .HasColumnName("roster_modifier_id");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rule_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_score_audit");

                    b.HasIndex("PickId")
                        .HasDatabaseName("ix_score_audit_pick_id");

                    b.HasIndex("RosterModifierId")
                        .HasDatabaseName("ix_score_audit_roster_modifier_id");

                    b.ToTable("score_audit");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.ScoringBonus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("params");

                    b.Property<long>("RulesetId")
                        .HasColumnType("bigint")
                        .HasColumnName("ruleset_id");

                    b.HasKey("Id")
                        .HasName("pk_scoring_bonus");

                    b.HasIndex("RulesetId")
                        .HasDatabaseName("ix_scoring_bonus_ruleset_id");

                    b.ToTable("scoring_bonus");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.ScoringRuleset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_scoring_ruleset");

                    b.HasIndex("SeasonId", "Source", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_ruleset_season_id_source_version");

                    b.ToTable("scoring_ruleset");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChampionshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("championship_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_season");

                    b.HasIndex("ChampionshipId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_season_championship_id_year");

                    b.ToTable("season");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint")
                        .HasColumnName("round_id");

                    b.Property<DateTime?>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_session_class_id");

                    b.HasIndex("RoundId", "ClassId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_session_round_id_class_id_type");

                    b.ToTable("session");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.CarEntry", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_car_entry_classes_class_id");

                    b.HasOne("ImsaFantasy.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_car_entry_seasons_season_id");

                    b.Navigation("Class");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Class", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Championship", "Championship")
                        .WithMany("Classes")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_championship_championship_id");

                    b.Navigation("Championship");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EmailEvent", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_email_event_app_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EmailPreference", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_preference_app_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EntityPrice", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_price_class_class_id");

                    b.HasOne("ImsaFantasy.Domain.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_price_rounds_round_id");

                    b.Navigation("Class");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EntryDriver", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.CarEntry", "CarEntry")
                        .WithMany("Lineup")
                        .HasForeignKey("CarEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entry_driver_car_entry_car_entry_id");

                    b.HasOne("ImsaFantasy.Domain.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entry_driver_driver_driver_id");

                    b.Navigation("CarEntry");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.EventReminder", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_reminder_event_event_id");

                    b.HasOne("ImsaFantasy.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_reminder_app_user_user_id");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.League", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Registration", "OwnerRegistration")
                        .WithMany()
                        .HasForeignKey("OwnerRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_registrations_owner_registration_id");

                    b.HasOne("ImsaFantasy.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_seasons_season_id");

                    b.Navigation("OwnerRegistration");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.LeagueMembership", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_membership_league_league_id");

                    b.HasOne("ImsaFantasy.Domain.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_membership_registrations_registration_id");

                    b.Navigation("League");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Pick", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pick_class_class_id");

                    b.HasOne("ImsaFantasy.Domain.Roster", "Roster")
                        .WithMany("Picks")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pick_rosters_roster_id");

                    b.Navigation("Class");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.PositionPoints", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.ScoringRuleset", "Ruleset")
                        .WithMany("PositionPoints")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_points_scoring_rulesets_ruleset_id");

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.QualiResult", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.CarEntry", "CarEntry")
                        .WithMany()
                        .HasForeignKey("CarEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quali_result_car_entry_car_entry_id");

                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quali_result_class_class_id");

                    b.HasOne("ImsaFantasy.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quali_result_sessions_session_id");

                    b.Navigation("CarEntry");

                    b.Navigation("Class");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RaceFastestLap", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_fastest_lap_class_class_id");

                    b.HasOne("ImsaFantasy.Domain.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_fastest_lap_driver_driver_id");

                    b.HasOne("ImsaFantasy.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_fastest_lap_sessions_session_id");

                    b.Navigation("Class");

                    b.Navigation("Driver");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RaceResult", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.CarEntry", "CarEntry")
                        .WithMany()
                        .HasForeignKey("CarEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_result_car_entry_car_entry_id");

                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_result_class_class_id");

                    b.HasOne("ImsaFantasy.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_race_result_sessions_session_id");

                    b.Navigation("CarEntry");

                    b.Navigation("Class");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Registration", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registration_seasons_season_id");

                    b.HasOne("ImsaFantasy.Domain.AppUser", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_registration_app_user_user_id");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Roster", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Registration", "Registration")
                        .WithMany("Rosters")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_registration_registration_id");

                    b.HasOne("ImsaFantasy.Domain.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_rounds_round_id");

                    b.Navigation("Registration");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RosterModifier", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Roster", "Roster")
                        .WithMany("Modifiers")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roster_modifier_roster_roster_id");

                    b.HasOne("ImsaFantasy.Domain.Pick", "TargetPick")
                        .WithMany()
                        .HasForeignKey("TargetPickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_modifier_pick_target_pick_id");

                    b.Navigation("Roster");

                    b.Navigation("TargetPick");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RosterModifierRule", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_modifier_rule_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RosterRule", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_rule_class_class_id");

                    b.HasOne("ImsaFantasy.Domain.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_rule_rounds_round_id");

                    b.HasOne("ImsaFantasy.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_rule_seasons_season_id");

                    b.Navigation("Class");

                    b.Navigation("Round");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Round", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Event", "Event")
                        .WithMany("Rounds")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_round_event_event_id");

                    b.HasOne("ImsaFantasy.Domain.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_round_seasons_season_id");

                    b.Navigation("Event");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.RoundTotal", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_round_total_registration_registration_id");

                    b.HasOne("ImsaFantasy.Domain.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_round_total_round_round_id");

                    b.Navigation("Registration");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Score", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Pick", "Pick")
                        .WithMany()
                        .HasForeignKey("PickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_score_pick_pick_id");

                    b.HasOne("ImsaFantasy.Domain.Roster", "Roster")
                        .WithMany()
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_score_roster_roster_id");

                    b.HasOne("ImsaFantasy.Domain.RosterModifier", "RosterModifier")
                        .WithMany()
                        .HasForeignKey("RosterModifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_score_roster_modifier_roster_modifier_id");

                    b.Navigation("Pick");

                    b.Navigation("Roster");

                    b.Navigation("RosterModifier");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.ScoreAudit", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Pick", "Pick")
                        .WithMany()
                        .HasForeignKey("PickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_score_audit_pick_pick_id");

                    b.HasOne("ImsaFantasy.Domain.RosterModifier", "RosterModifier")
                        .WithMany()
                        .HasForeignKey("RosterModifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_score_audit_roster_modifier_roster_modifier_id");

                    b.Navigation("Pick");

                    b.Navigation("RosterModifier");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.ScoringBonus", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.ScoringRuleset", "Ruleset")
                        .WithMany("Bonuses")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_bonus_scoring_rulesets_ruleset_id");

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.ScoringRuleset", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_ruleset_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Season", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Championship", "Championship")
                        .WithMany("Seasons")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_season_championship_championship_id");

                    b.Navigation("Championship");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Session", b =>
                {
                    b.HasOne("ImsaFantasy.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_class_class_id");

                    b.HasOne("ImsaFantasy.Domain.Round", "Round")
                        .WithMany("Sessions")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_round_round_id");

                    b.Navigation("Class");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.AppUser", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.CarEntry", b =>
                {
                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Championship", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Event", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.League", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Registration", b =>
                {
                    b.Navigation("Rosters");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Roster", b =>
                {
                    b.Navigation("Modifiers");

                    b.Navigation("Picks");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Round", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.ScoringRuleset", b =>
                {
                    b.Navigation("Bonuses");

                    b.Navigation("PositionPoints");
                });

            modelBuilder.Entity("ImsaFantasy.Domain.Season", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
